### PR TITLE
link to blog for fastgo

### PR DESCRIPTION
**Pull request by jayenashar**
brian and i are making updates on skedgo.com

### CODE REVIEW

**Comment by nighthawk** [comment]
Link works fine. Mariano, can you double check that all is there? Also the end of the blog post should point to part 2 as that's now been published.

**Comment by jayenashar** [comment]
is there going to be a part 3?  i saw a mention of it somewhere.

**Comment by nighthawk** [comment]
Part 2 says part 3 will cover trip updates.

**Comment by MarianoTucat** [comment]
Just checked it, the blog post on skedgo.com LGTM.

**Pull request merged**
